
version: 2

models:
  # - name: my_first_dbt_model
  #   description: "A starter dbt model"
  #   columns:
  #     - name: id
  #       description: "The primary key for this table"
  #       data_tests:
  #         - unique
  #         #- not_null
  #         # - accepted_values:
  #         #     values: [1, 2]
  #         #     quote: false

  # - name: my_second_dbt_model
  #   description: "A starter dbt model"
  #   columns:
  #     - name: id
  #       description: "The primary key for this table"
  #       data_tests:
  #         - unique
  #         #- not_null
  #         - relationships:
  #             to: ref('my_first_dbt_model')
  #             field: id

  # - name: snowflake_customer_purchases
  #   description: "the total purchases for each customer in snowflake sample data"
  #   columns:
  #     - name: c_custkey
  #       tests: 
  #         - unique
  #         - not_null

  # - name: snowflake_customer_purchases_daily          
  #   description: "the total daily purchases for each customer in snowflake sample data"
  #   columns:
  #     - name: c_custkey
  #       tests: 
  #         - unique
  #         - not_null

  # - name: dates
  # - name: assignement_incremental_time  

  - name: playing_with_tests
    description: "playing_with_tests"
    columns:
      - name: c_custkey
        data_tests:
          - unique
          - not_null
      - name: c_mktsegment
        data_tests:
          - unique
          - not_null
          - accepted_values:
              values: ['BUILDING', 'AUTOMOBILE', 'MACHINERY', 'HOUSEHOLD', 'FURNITURE']
              quote: False

          # - accepted_values:
          #     values: [1, 2]
          #     quote: false